version: 1.0.{build}
os: Visual Studio 2015
test: off
platform:
- x86
- x64
environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
  - CONDA: 27
  - CONDA: 35
install:
- ps: |
    if ($env:PLATFORM -eq "x64") { $env:CMAKE_ARCH = "x64" }
    if ($env:PYTHON) {
      if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
      $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
      pip install --disable-pip-version-check --user --upgrade pip wheel
      pip install numpy scipy
    } elseif ($env:CONDA) {
      if ($env:CONDA -eq "27") { $env:CONDA = "" }
      if ($env:PLATFORM -eq "x64") { $env:CONDA = "$env:CONDA-x64" }
      $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"
      conda install -y -q numpy scipy
    }
- ps: |
    Start-FileDownload 'http://bitbucket.org/eigen/eigen/get/3.2.9.zip'
    7z x 3.2.9.zip -y > $null
    $env:CMAKE_INCLUDE_PATH = "eigen-eigen-dc6cfdf9bcec"
build_script:
- cmake -A "%CMAKE_ARCH%"
- set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmake --build . --config Release --target check -- /v:m /logger:%MSBuildLogger%
