language: cpp
sudo: false
matrix:
  include:
  - os: linux
    compiler: gcc-4.8
    env: PYTHON=2.7 CPP=11
  - os: linux
    compiler: gcc-4.8
    env: PYTHON=3.5 CPP=11
  - os: osx
    osx_image: xcode7.3
    env: PYTHON=2.7 CPP=14
  - os: osx
    osx_image: xcode7.3
    env: PYTHON=3.5 CPP=14
cache:
  directories:
  - $HOME/.cache/pip
  - ccache
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
      - kubuntu-backports # cmake 2.8.12
    packages:
      - g++-4.8
      - python3.5
      - python3.5-dev
      - cmake
install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    export CXX=g++-4.8 CC=gcc-4.8;
    pip install --user --upgrade pip virtualenv
    virtualenv -p python$PYTHON venv
  elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
    if [ "${PYTHON:0:1}" = "3" ]; then
      PMAJOR=3; brew update; brew install python$PMAJOR;
    else
      curl -fsSL -O https://bootstrap.pypa.io/get-pip.py
      sudo -H python get-pip.py
    fi
    pip$PMAJOR install --user --upgrade pip virtualenv
    python$PMAJOR -m virtualenv venv
  fi
  source venv/bin/activate
  pip install numpy scipy
- |
  wget -q -O eigen.tar.gz https://bitbucket.org/eigen/eigen/get/3.2.9.tar.gz
  tar xzf eigen.tar.gz
  export CMAKE_INCLUDE_PATH=eigen-eigen-dc6cfdf9bcec
script:
- cmake -DPYBIND11_PYTHON_VERSION=$PYTHON -DPYBIND11_CPP_STANDARD=-std=c++$CPP
- CTEST_OUTPUT_ON_FAILURE=TRUE make check -j 2
